RADE-32 added home, login, signup to the pages folder
ProgiRade/bytepit-ui pull request #4
Opened 2023-11-06 10:38 UTC by filipides1

2023-11-06 22:32 UTC, TeoMatosevic commented on bytepit-ui/src/pages/index.ts
> +    RegisterPage
Add "," to the end of "RegisterPage"

2023-11-06 22:32 UTC, TeoMatosevic commented on bytepit-ui/src/pages/index.ts
> +
Remove this line

2023-11-06 22:33 UTC, TeoMatosevic requested changes
Make minor changes

2023-11-07 10:48 UTC, TeoMatosevic approved these changes

2023-11-07 13:48 UTC, TelurijevDioksid approved these changes

2023-11-07 14:01 UTC, merged